{{- if eq .Values.ragApi.workloadType "knativeService" }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "librechat-mt.fullname" . }}-rag-api
  labels:
    {{- include "librechat-mt.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rag-api
        {{- include "librechat-mt.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.ragApi.image.repository }}:{{ .Values.ragApi.image.tag }}"
{{- end }}

